{% set name = "markovify" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eac0a156ed54bb6bede32ef20131813fbec9db70b515ead57b4d8887a16dfe39

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}
    - unidecode

test:
  imports:
    - markovify
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jsvine/markovify
  # Non MANIFEST - see https://github.com/jsvine/markovify/pull/65
  license_file: {{ RECIPE_DIR }}/LICENSE.txt
  license: MIT
  license_family: MIT
  summary: A simple, extensible Markov chain generator. Uses include generating random semi-plausible sentences based on an existing text.
  dev_url: https://github.com/jsvine/markovify
  doc_url: https://github.com/jsvine/markovify

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
