{% set name = "markovify" %}
{% set version = "0.6.2" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "718c52aff48162aae9475d0a98015c75f839af989f26ec766d83afd46d400fe3" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - unidecode

test:
  imports:
    - markovify

about:
  home: https://github.com/jsvine/markovify
  # Non MANIFEST - see https://github.com/jsvine/markovify/pull/65
  license_file: {{ RECIPE_DIR }}/LICENSE.txt
  license: MIT
  license_family: MIT
  summary: 'A simple, extensible Markov chain generator. Uses include generating random semi-plausible sentences based on an existing text.'
  dev_url: https://github.com/jsvine/markovify
  doc_url: https://github.com/jsvine/markovify

extra:
  recipe-maintainers:
    - pmlandwehr
