travis:
  secure:
    BINSTAR_TOKEN: FMtJIc55lNdudlOQHdtQ3ERcRvTC62wttFhlRjEVHHF5FO1YljxduHZOQ2U6R+yQAQxZa/IMMVcQiPpM3ZtT5YyIxcSpUiJ8kygfDo90Jln+FMtmqGXxdIxkt9lAmz5YtNZfoXN7za0w6JezOkOFONQ/a3LDNXxrSga2oW1EVjk/ABJJt5RNR8Iy/fLfmcbJsjETS9eo91kyYp6BRt1qrtMK5ndMoCPnIuHyM9dVrj2D1C+j9q63BCx9BaXBT5P1MYOoTQzOkDt+iF267Wt3jfC2v1uWI77M6l6ap0PF0I90lD3bGuKP2QkG5J6obGznWIJBI2VJtdn11h5mvkcv+t1fkD1YHUcjbKTwKRceOtUl/BSDzcsGDNo18xshAelwuQ4wc/4mkO25grpqFGmygJNERvxZGP948WHthNWyMa9E1phro0lQX/v1Mdy8s1QFykfYBwUoQyVtWn0UjOxP+lE/Z7fWCXHMV6LHSAHzEuW3o6LWqZR5u1lCrw9oBO0Yc8l1M34nSIOv0jNCjD1EN26rmwGSvfRWOcxTIShdBcJAhNJvUTZdLmSMfslvjrhSXCABTv2gK37i+mSlaw2l7h0iXnMF4yBUA/t1VtVSNPIyI+xU5UL7d+0IhOVu6hpDyCwKrUm8Jy8hkkmPIaZ+r9iFU+kJ7///2UObuTSFG3g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
