travis:
  secure:
    BINSTAR_TOKEN: Ta7pJ6IAaXKbxnvoAqMEIPueiVt/gpAph5Mro/tINzIAfByIrzvtvV5eMaOP0qT5Iie/lTJ02I9QUUCeznuqCAuzPu5ZN0pJr8k2SMzDTTeLqHby58J7sKsZqu+NpZ5yO/IMWBHTumeSAib7BibZDziUQkaEFnG9I9L5T9uYU3Dy2Z1DuYDInb1InDN7AXrW/XmRYSqgPvB2ZuwPSpU4MmGBPdioetqzqo98KJO1X7jFhx0Gs+d4ku0uu/NL0BPNF2qbEGyuV+n3/nE5aGRU/y7z7Yz4Cu3eic5oEvYCjg1/3Q01jFGwOiq8sc3eBZrFWDjI1vRjqCxLHKsZmKbodd1yL+UMEl1rXobrBFY0wYl6SyfaO0FxX+n+jWFgmbbjVi7fDYQoUQxKLxoeDScsbnY54iWG4WMJixDRN5sylUOkLLYeLSq0Bl8qm8qin/rhE+Wru+vWjlqKkccpYvD3hKpHIEDlSszA4iuil/QO6r/xnTrM4T+YC1k9vVEPBnh3SC6QSFIsqnKPM0IwSxlgp6yJ362tMlSsUx+sLBF0Qn3WaU4Egq7JdrQyje+skZ4lmm7tiDHv9iALKQIrymx9cotB30LxKcEZZrGZ68uuSrvaClW8fd4sJN1LGq8a8fZdpwSUPwmEVwz5gTPi+9xBEmcxcUBHGfIWP3f+LAUv2SA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
